sessions:
  advanced_example:
    root: ~/projects/advanced
    env:
      PROJECT_ENV: production
    windows:
      - name: Editor
        layout: main-vertical
        panes:
          - command: nvim main.py
          - command: nvim test_main.py
      - name: Servers
        layout: tiled
        panes:
          - command: python app.py
          - command: python worker.py
          - command: redis-server
          - command: mongod
      - name: Logs
        command: tail -f logs/app.log
