sessions:
  exmaple:
    root: ~/projects/advanced
    env:
      PROJECT_ENV: production
    windows:
      - name: Editor
        layout: main-vertical
        panes:
          - command: nvim main.py
          - command: nvim test_main.py
      - name: Servers
        layout: tiled
        panes:
          - command: python app.py
          - command: python worker.py
          - command: redis-server
          - command: mongod
      - name: Logs
        command: tail -f logs/app.log
  mini:
    root: ~/CommonCore/3.MiniShell/
    env:
      PROJECT_ENV: production
    windows:
      - name: Editor
        layout: main-vertical
        panes:
          - command: nvim ~/CommonCore/3.MiniShell/src/
      - name: Compiling
        layout: tiled
        panes:
          - command: pwd
      - name: README
        command: nvim ~/CommonCore/3.MiniShell/README.md
