sessions:
  example:
    root: ~/CommonCore/4.CPP/
    start_index: 1
    windows:
      - name: Editor
        command: nvim ~/CommonCore/4.CPP/CPP00/
      - name: Compilation
        command: ls
      - name: Logs
        command: tail -f /var/log/syslog

  mini:
    root: ~/CommonCore/3.MiniShell/
    start_index: 1
    windows:
      - name: Editor
        command: nvim ~/CommonCore/3.MiniShell/src/
      - name: Compiling
        command: make
      - name: README
        command: nvim ~/CommonCore/3.MiniShell/README.md
